[theme]

primary = '#48BF91'
secondary = '#4CB4D7'
tertiary = '#0076BE'

# Background color for the main content area
backgroundColor = '#F0F0F0'

# Color used for almost all text
textColor = '#FFFFFF'
